import {
  Product,
  MpesaAccount,
  User,
  InventoryItem,
  BusinessProfile,
  BusinessPartner,
  InterBusinessTransfer,
} from '../types';

export const INITIAL_BUSINESSES: BusinessProfile[] = [
  {
    id: 'biz-1',
    name: 'Bar Tracker Lounge',
    connectCode: '849201',
    phone: '0722 000 000',
    ownerName: 'Proprietor',
    address: 'Nairobi, Kenya',
  },
];

export const INITIAL_PARTNERS: BusinessPartner[] = [];

export const INITIAL_TRANSFERS: InterBusinessTransfer[] = [];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-1',
    businessId: 'biz-1',
    username: 'wanjiku',
    name: 'Wanjiku Kamau (Bar Tender)',
    role: 'WORKER',
    pinCode: '1234',
    password: 'password123',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-2',
    businessId: 'biz-1',
    username: 'kevin',
    name: 'Kevin Omondi (Bar Tender)',
    role: 'WORKER',
    pinCode: '5678',
    password: 'password123',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-owner',
    businessId: 'biz-1',
    username: 'ann_njeri',
    name: 'Ann Njeri (Proprietor)',
    role: 'OWNER',
    pinCode: '8888',
    password: 'password123',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-owner-mary',
    businessId: 'biz-1',
    username: 'mary',
    name: 'Mary Mwihaki',
    role: 'OWNER',
    pinCode: '8888',
    password: 'password123',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_MPESA_ACCOUNTS: MpesaAccount[] = [
  {
    id: 'mpesa-till-1',
    accountName: 'Bar Buy Goods Till',
    accountType: 'BUY_GOODS_TILL',
    identifier: '5421980',
    currentBalance: 14200,
  },
  {
    id: 'mpesa-paybill-1',
    accountName: 'Business Paybill 889900',
    accountType: 'PAYBILL',
    identifier: '889900 (Acc: BAR)',
    currentBalance: 32000,
  },
  {
    id: 'mpesa-pochi-1',
    accountName: 'Manager Pochi la Biashara',
    accountType: 'POCHI_LA_BIASHARA',
    identifier: '0722 841 902',
    currentBalance: 8500,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-tusker-500',
    name: 'Tusker Lager 500ml',
    category: 'BEER',
    unit: 'BOTTLE',
    costPrice: 190,
    sellingPrice: 260,
    reorderLevel: 5,
    volumeMl: 500,
  },
  {
    id: 'prod-tusker-malt',
    name: 'Tusker Malt 330ml',
    category: 'BEER',
    unit: 'BOTTLE',
    costPrice: 210,
    sellingPrice: 280,
    reorderLevel: 5,
    volumeMl: 330,
  },
  {
    id: 'prod-tusker-cider',
    name: 'Tusker Cider 500ml',
    category: 'CIDER',
    unit: 'BOTTLE',
    costPrice: 210,
    sellingPrice: 280,
    reorderLevel: 5,
    volumeMl: 500,
  },
  {
    id: 'prod-white-cap',
    name: 'White Cap Crisp 500ml',
    category: 'BEER',
    unit: 'BOTTLE',
    costPrice: 200,
    sellingPrice: 270,
    reorderLevel: 5,
    volumeMl: 500,
  },
  {
    id: 'prod-guinness',
    name: 'Guinness Foreign Extra 500ml',
    category: 'BEER',
    unit: 'BOTTLE',
    costPrice: 220,
    sellingPrice: 300,
    reorderLevel: 5,
    volumeMl: 500,
  },
  {
    id: 'prod-heineken',
    name: 'Heineken Lager 500ml',
    category: 'BEER',
    unit: 'CAN',
    costPrice: 240,
    sellingPrice: 350,
    reorderLevel: 5,
    volumeMl: 500,
  },
  {
    id: 'prod-balozi',
    name: 'Balozi Lager 500ml',
    category: 'BEER',
    unit: 'BOTTLE',
    costPrice: 180,
    sellingPrice: 250,
    reorderLevel: 5,
    volumeMl: 500,
  },
  {
    id: 'prod-jw-black',
    name: 'Johnnie Walker Black Label 750ml',
    category: 'SPIRIT',
    unit: 'BOTTLE',
    costPrice: 3400,
    sellingPrice: 4800,
    reorderLevel: 5,
    volumeMl: 750,
  },
  {
    id: 'prod-jameson',
    name: 'Jameson Irish Whiskey 750ml',
    category: 'SPIRIT',
    unit: 'BOTTLE',
    costPrice: 2800,
    sellingPrice: 4000,
    reorderLevel: 5,
    volumeMl: 750,
  },
  {
    id: 'prod-gilbeys',
    name: 'Gilbeys Special Dry Gin 750ml',
    category: 'SPIRIT',
    unit: 'BOTTLE',
    costPrice: 1350,
    sellingPrice: 2000,
    reorderLevel: 5,
    volumeMl: 750,
  },
  {
    id: 'prod-captain-morgan',
    name: 'Captain Morgan Gold 750ml',
    category: 'SPIRIT',
    unit: 'BOTTLE',
    costPrice: 1250,
    sellingPrice: 1800,
    reorderLevel: 5,
    volumeMl: 750,
  },
  {
    id: 'prod-coke',
    name: 'Coca Cola 300ml Glass',
    category: 'SOFT_DRINK',
    unit: 'BOTTLE',
    costPrice: 60,
    sellingPrice: 100,
    reorderLevel: 5,
    volumeMl: 300,
  },
  {
    id: 'prod-krest',
    name: 'Krest Bitter Lemon 300ml',
    category: 'SOFT_DRINK',
    unit: 'BOTTLE',
    costPrice: 70,
    sellingPrice: 120,
    reorderLevel: 5,
    volumeMl: 300,
  },
  {
    id: 'prod-redbull',
    name: 'Red Bull Energy 250ml',
    category: 'SOFT_DRINK',
    unit: 'CAN',
    costPrice: 200,
    sellingPrice: 300,
    reorderLevel: 5,
    volumeMl: 250,
  },
];

// Standalone Bar Inventory
export const INITIAL_INVENTORY: InventoryItem[] = [
  { productId: 'prod-tusker-500', quantityOnHand: 48, updatedAt: new Date().toISOString() },
  { productId: 'prod-tusker-malt', quantityOnHand: 24, updatedAt: new Date().toISOString() },
  { productId: 'prod-tusker-cider', quantityOnHand: 36, updatedAt: new Date().toISOString() },
  { productId: 'prod-white-cap', quantityOnHand: 30, updatedAt: new Date().toISOString() },
  { productId: 'prod-guinness', quantityOnHand: 32, updatedAt: new Date().toISOString() },
  { productId: 'prod-heineken', quantityOnHand: 18, updatedAt: new Date().toISOString() },
  { productId: 'prod-balozi', quantityOnHand: 24, updatedAt: new Date().toISOString() },
  { productId: 'prod-jw-black', quantityOnHand: 5, updatedAt: new Date().toISOString() },
  { productId: 'prod-jameson', quantityOnHand: 7, updatedAt: new Date().toISOString() },
  { productId: 'prod-gilbeys', quantityOnHand: 9, updatedAt: new Date().toISOString() },
  { productId: 'prod-captain-morgan', quantityOnHand: 6, updatedAt: new Date().toISOString() },
  { productId: 'prod-coke', quantityOnHand: 40, updatedAt: new Date().toISOString() },
  { productId: 'prod-krest', quantityOnHand: 24, updatedAt: new Date().toISOString() },
  { productId: 'prod-redbull', quantityOnHand: 20, updatedAt: new Date().toISOString() },
];
