import {
  Product,
  StockLocation,
  MpesaAccount,
  User,
  InventoryItem,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Wanjiku Kamau (Bar Tender)',
    role: 'WORKER',
    pinCode: '1234',
    assignedLocationId: 'loc-counter-1',
  },
  {
    id: 'user-2',
    name: 'Kevin Omondi (VIP Counter)',
    role: 'WORKER',
    pinCode: '5678',
    assignedLocationId: 'loc-counter-vip',
  },
  {
    id: 'user-owner',
    name: 'Maina Mwangi (Proprietor)',
    role: 'OWNER',
    pinCode: '8888',
  },
];

export const INITIAL_LOCATIONS: StockLocation[] = [
  {
    id: 'loc-store',
    name: 'Central Warehouse / Store',
    branchId: 'branch-1',
    isCounter: false,
  },
  {
    id: 'loc-counter-1',
    name: 'Main Counter Station',
    branchId: 'branch-1',
    isCounter: true,
  },
  {
    id: 'loc-counter-vip',
    name: 'VIP Lounge Bar',
    branchId: 'branch-1',
    isCounter: true,
  },
  {
    id: 'loc-counter-terrace',
    name: 'Terrace Garden Counter',
    branchId: 'branch-1',
    isCounter: true,
  },
];

export const INITIAL_MPESA_ACCOUNTS: MpesaAccount[] = [
  {
    id: 'mpesa-till-1',
    branchId: 'branch-1',
    accountName: 'Bar Counter Buy Goods Till',
    accountType: 'BUY_GOODS_TILL',
    identifier: '5421980',
    currentBalance: 14200,
  },
  {
    id: 'mpesa-paybill-1',
    branchId: 'branch-1',
    accountName: 'Business Paybill 889900',
    accountType: 'PAYBILL',
    identifier: '889900 (Acc: COUNTER)',
    currentBalance: 32000,
  },
  {
    id: 'mpesa-pochi-1',
    branchId: 'branch-1',
    accountName: 'Manager Pochi la Biashara',
    accountType: 'POCHI_LA_BIASHARA',
    identifier: '0722 841 902',
    currentBalance: 8500,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-tusker-500',
    name: 'Tusker Lager 500ml',
    category: 'BEER',
    unit: 'BOTTLE',
    costPrice: 190,
    sellingPrice: 260,
    reorderLevel: 24,
    volumeMl: 500,
  },
  {
    id: 'prod-tusker-malt',
    name: 'Tusker Malt 330ml',
    category: 'BEER',
    unit: 'BOTTLE',
    costPrice: 200,
    sellingPrice: 280,
    reorderLevel: 24,
    volumeMl: 330,
  },
  {
    id: 'prod-tusker-cider',
    name: 'Tusker Cider 500ml',
    category: 'CIDER',
    unit: 'BOTTLE',
    costPrice: 210,
    sellingPrice: 300,
    reorderLevel: 24,
    volumeMl: 500,
  },
  {
    id: 'prod-white-cap',
    name: 'White Cap Lager 500ml',
    category: 'BEER',
    unit: 'BOTTLE',
    costPrice: 195,
    sellingPrice: 270,
    reorderLevel: 24,
    volumeMl: 500,
  },
  {
    id: 'prod-guinness',
    name: 'Guinness Foreign Extra 500ml',
    category: 'BEER',
    unit: 'BOTTLE',
    costPrice: 220,
    sellingPrice: 300,
    reorderLevel: 24,
    volumeMl: 500,
  },
  {
    id: 'prod-heineken',
    name: 'Heineken Lager 330ml',
    category: 'BEER',
    unit: 'BOTTLE',
    costPrice: 240,
    sellingPrice: 350,
    reorderLevel: 12,
    volumeMl: 330,
  },
  {
    id: 'prod-balozi',
    name: 'Balozi Lager 500ml',
    category: 'BEER',
    unit: 'BOTTLE',
    costPrice: 180,
    sellingPrice: 250,
    reorderLevel: 24,
    volumeMl: 500,
  },
  {
    id: 'prod-jw-black',
    name: 'Johnnie Walker Black Label 750ml',
    category: 'SPIRIT',
    unit: 'BOTTLE',
    costPrice: 3400,
    sellingPrice: 4800,
    reorderLevel: 6,
    volumeMl: 750,
  },
  {
    id: 'prod-jameson',
    name: 'Jameson Irish Whiskey 750ml',
    category: 'SPIRIT',
    unit: 'BOTTLE',
    costPrice: 2600,
    sellingPrice: 3800,
    reorderLevel: 6,
    volumeMl: 750,
  },
  {
    id: 'prod-gilbeys',
    name: 'Gilbeys Special Dry Gin 750ml',
    category: 'SPIRIT',
    unit: 'BOTTLE',
    costPrice: 1300,
    sellingPrice: 2100,
    reorderLevel: 8,
    volumeMl: 750,
  },
  {
    id: 'prod-captain-morgan',
    name: 'Captain Morgan Spiced Gold 750ml',
    category: 'SPIRIT',
    unit: 'BOTTLE',
    costPrice: 1400,
    sellingPrice: 2200,
    reorderLevel: 6,
    volumeMl: 750,
  },
  {
    id: 'prod-coke',
    name: 'Coca-Cola 300ml Glass',
    category: 'SOFT_DRINK',
    unit: 'BOTTLE',
    costPrice: 60,
    sellingPrice: 100,
    reorderLevel: 24,
    volumeMl: 300,
  },
  {
    id: 'prod-krest',
    name: 'Krest Bitter Lemon 300ml',
    category: 'SOFT_DRINK',
    unit: 'BOTTLE',
    costPrice: 70,
    sellingPrice: 120,
    reorderLevel: 24,
    volumeMl: 300,
  },
  {
    id: 'prod-redbull',
    name: 'Red Bull Energy 250ml',
    category: 'SOFT_DRINK',
    unit: 'CAN',
    costPrice: 200,
    sellingPrice: 300,
    reorderLevel: 12,
    volumeMl: 250,
  },
];

// Initial stock at Counter 1 (Main Bar) for immediate realistic testing
export const INITIAL_INVENTORY: InventoryItem[] = [
  { productId: 'prod-tusker-500', locationId: 'loc-counter-1', quantityOnHand: 48, updatedAt: new Date().toISOString() },
  { productId: 'prod-tusker-malt', locationId: 'loc-counter-1', quantityOnHand: 24, updatedAt: new Date().toISOString() },
  { productId: 'prod-tusker-cider', locationId: 'loc-counter-1', quantityOnHand: 36, updatedAt: new Date().toISOString() },
  { productId: 'prod-white-cap', locationId: 'loc-counter-1', quantityOnHand: 30, updatedAt: new Date().toISOString() },
  { productId: 'prod-guinness', locationId: 'loc-counter-1', quantityOnHand: 32, updatedAt: new Date().toISOString() },
  { productId: 'prod-heineken', locationId: 'loc-counter-1', quantityOnHand: 18, updatedAt: new Date().toISOString() },
  { productId: 'prod-balozi', locationId: 'loc-counter-1', quantityOnHand: 24, updatedAt: new Date().toISOString() },
  { productId: 'prod-jw-black', locationId: 'loc-counter-1', quantityOnHand: 5, updatedAt: new Date().toISOString() },
  { productId: 'prod-jameson', locationId: 'loc-counter-1', quantityOnHand: 7, updatedAt: new Date().toISOString() },
  { productId: 'prod-gilbeys', locationId: 'loc-counter-1', quantityOnHand: 9, updatedAt: new Date().toISOString() },
  { productId: 'prod-captain-morgan', locationId: 'loc-counter-1', quantityOnHand: 6, updatedAt: new Date().toISOString() },
  { productId: 'prod-coke', locationId: 'loc-counter-1', quantityOnHand: 40, updatedAt: new Date().toISOString() },
  { productId: 'prod-krest', locationId: 'loc-counter-1', quantityOnHand: 24, updatedAt: new Date().toISOString() },
  { productId: 'prod-redbull', locationId: 'loc-counter-1', quantityOnHand: 20, updatedAt: new Date().toISOString() },

  // Warehouse reserves
  { productId: 'prod-tusker-500', locationId: 'loc-store', quantityOnHand: 240, updatedAt: new Date().toISOString() },
  { productId: 'prod-tusker-cider', locationId: 'loc-store', quantityOnHand: 120, updatedAt: new Date().toISOString() },
  { productId: 'prod-guinness', locationId: 'loc-store', quantityOnHand: 144, updatedAt: new Date().toISOString() },
  { productId: 'prod-jw-black', locationId: 'loc-store', quantityOnHand: 24, updatedAt: new Date().toISOString() },
  { productId: 'prod-jameson', locationId: 'loc-store', quantityOnHand: 30, updatedAt: new Date().toISOString() },
];
