import {
  Product,
  MpesaAccount,
  User,
  InventoryItem,
  BusinessProfile,
  BusinessPartner,
  InterBusinessTransfer,
} from '../types';

export const INITIAL_BUSINESSES: BusinessProfile[] = [
  {
    id: 'biz-1',
    name: 'The Alchemist Bar',
    connectCode: '849201',
    phone: '0722 841 902',
    ownerName: 'Maina Mwangi',
    address: 'Parklands Road, Westlands',
  },
  {
    id: 'biz-2',
    name: 'The Copper Kettle Lounge',
    connectCode: '512784',
    phone: '0733 456 789',
    ownerName: 'James Kariuki',
    address: 'Kenyatta Avenue, CBD',
  },
  {
    id: 'biz-3',
    name: 'Brew Bistro & Taproom',
    connectCode: '394108',
    phone: '0711 987 654',
    ownerName: 'Sarah Mutua',
    address: 'Piedmont Plaza, Ngong Rd',
  },
];

export const INITIAL_PARTNERS: BusinessPartner[] = [
  {
    id: 'partner-1-2',
    businessId: 'biz-1',
    partnerBusinessId: 'biz-2',
    partnerName: 'The Copper Kettle Lounge',
    partnerPhone: '0733 456 789',
    partnerConnectCode: '512784',
    netCostBalance: 4560, // Copper Kettle owes Alchemist KES 4,560 for 24 Tuskers
    connectedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'partner-2-1',
    businessId: 'biz-2',
    partnerBusinessId: 'biz-1',
    partnerName: 'The Alchemist Bar',
    partnerPhone: '0722 841 902',
    partnerConnectCode: '849201',
    netCostBalance: -4560, // Copper Kettle owes Alchemist
    connectedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
];

export const INITIAL_TRANSFERS: InterBusinessTransfer[] = [
  {
    id: 'trf-sample-1',
    fromBusinessId: 'biz-1',
    fromBusinessName: 'The Alchemist Bar',
    fromShiftId: 'shift-sample-closed',
    senderWorkerName: 'Wanjiku Kamau (Bar Tender)',
    toBusinessId: 'biz-2',
    toBusinessName: 'The Copper Kettle Lounge',
    receiverWorkerName: 'Peter Mwiti',
    productId: 'prod-tusker-500',
    productName: 'Tusker Lager 500ml',
    quantity: 24,
    unitCost: 190,
    totalCostValue: 4560,
    status: 'ACCEPTED',
    dispatchedAt: new Date(Date.now() - 3600000 * 20).toISOString(),
    acceptedAt: new Date(Date.now() - 3600000 * 19).toISOString(),
    notes: 'Emergency crate borrowed during Friday night rush',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-1',
    businessId: 'biz-1',
    username: 'wanjiku',
    name: 'Wanjiku Kamau (Bar Tender)',
    role: 'WORKER',
    pinCode: '1234',
    password: 'password123',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-2',
    businessId: 'biz-1',
    username: 'kevin',
    name: 'Kevin Omondi (Bar Tender)',
    role: 'WORKER',
    pinCode: '5678',
    password: 'password123',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-owner',
    businessId: 'biz-1',
    username: 'maina',
    name: 'Maina Mwangi (Proprietor)',
    role: 'OWNER',
    pinCode: '8888',
    password: 'adminpassword',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_MPESA_ACCOUNTS: MpesaAccount[] = [
  {
    id: 'mpesa-till-1',
    accountName: 'Bar Buy Goods Till',
    accountType: 'BUY_GOODS_TILL',
    identifier: '5421980',
    currentBalance: 14200,
  },
  {
    id: 'mpesa-paybill-1',
    accountName: 'Business Paybill 889900',
    accountType: 'PAYBILL',
    identifier: '889900 (Acc: BAR)',
    currentBalance: 32000,
  },
  {
    id: 'mpesa-pochi-1',
    accountName: 'Manager Pochi la Biashara',
    accountType: 'POCHI_LA_BIASHARA',
    identifier: '0722 841 902',
    currentBalance: 8500,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-tusker-500',
    name: 'Tusker Lager 500ml',
    category: 'BEER',
    unit: 'BOTTLE',
    costPrice: 190,
    sellingPrice: 260,
    reorderLevel: 5,
    volumeMl: 500,
  },
  {
    id: 'prod-tusker-malt',
    name: 'Tusker Malt 330ml',
    category: 'BEER',
    unit: 'BOTTLE',
    costPrice: 210,
    sellingPrice: 280,
    reorderLevel: 5,
    volumeMl: 330,
  },
  {
    id: 'prod-tusker-cider',
    name: 'Tusker Cider 500ml',
    category: 'CIDER',
    unit: 'BOTTLE',
    costPrice: 210,
    sellingPrice: 280,
    reorderLevel: 5,
    volumeMl: 500,
  },
  {
    id: 'prod-white-cap',
    name: 'White Cap Crisp 500ml',
    category: 'BEER',
    unit: 'BOTTLE',
    costPrice: 200,
    sellingPrice: 270,
    reorderLevel: 5,
    volumeMl: 500,
  },
  {
    id: 'prod-guinness',
    name: 'Guinness Foreign Extra 500ml',
    category: 'BEER',
    unit: 'BOTTLE',
    costPrice: 220,
    sellingPrice: 300,
    reorderLevel: 5,
    volumeMl: 500,
  },
  {
    id: 'prod-heineken',
    name: 'Heineken Lager 500ml',
    category: 'BEER',
    unit: 'CAN',
    costPrice: 240,
    sellingPrice: 350,
    reorderLevel: 5,
    volumeMl: 500,
  },
  {
    id: 'prod-balozi',
    name: 'Balozi Lager 500ml',
    category: 'BEER',
    unit: 'BOTTLE',
    costPrice: 180,
    sellingPrice: 250,
    reorderLevel: 5,
    volumeMl: 500,
  },
  {
    id: 'prod-jw-black',
    name: 'Johnnie Walker Black Label 750ml',
    category: 'SPIRIT',
    unit: 'BOTTLE',
    costPrice: 3400,
    sellingPrice: 4800,
    reorderLevel: 5,
    volumeMl: 750,
  },
  {
    id: 'prod-jameson',
    name: 'Jameson Irish Whiskey 750ml',
    category: 'SPIRIT',
    unit: 'BOTTLE',
    costPrice: 2800,
    sellingPrice: 4000,
    reorderLevel: 5,
    volumeMl: 750,
  },
  {
    id: 'prod-gilbeys',
    name: 'Gilbeys Special Dry Gin 750ml',
    category: 'SPIRIT',
    unit: 'BOTTLE',
    costPrice: 1350,
    sellingPrice: 2000,
    reorderLevel: 5,
    volumeMl: 750,
  },
  {
    id: 'prod-captain-morgan',
    name: 'Captain Morgan Gold 750ml',
    category: 'SPIRIT',
    unit: 'BOTTLE',
    costPrice: 1250,
    sellingPrice: 1800,
    reorderLevel: 5,
    volumeMl: 750,
  },
  {
    id: 'prod-coke',
    name: 'Coca Cola 300ml Glass',
    category: 'SOFT_DRINK',
    unit: 'BOTTLE',
    costPrice: 60,
    sellingPrice: 100,
    reorderLevel: 5,
    volumeMl: 300,
  },
  {
    id: 'prod-krest',
    name: 'Krest Bitter Lemon 300ml',
    category: 'SOFT_DRINK',
    unit: 'BOTTLE',
    costPrice: 70,
    sellingPrice: 120,
    reorderLevel: 5,
    volumeMl: 300,
  },
  {
    id: 'prod-redbull',
    name: 'Red Bull Energy 250ml',
    category: 'SOFT_DRINK',
    unit: 'CAN',
    costPrice: 200,
    sellingPrice: 300,
    reorderLevel: 5,
    volumeMl: 250,
  },
];

// Standalone Bar Inventory
export const INITIAL_INVENTORY: InventoryItem[] = [
  { productId: 'prod-tusker-500', quantityOnHand: 48, updatedAt: new Date().toISOString() },
  { productId: 'prod-tusker-malt', quantityOnHand: 24, updatedAt: new Date().toISOString() },
  { productId: 'prod-tusker-cider', quantityOnHand: 36, updatedAt: new Date().toISOString() },
  { productId: 'prod-white-cap', quantityOnHand: 30, updatedAt: new Date().toISOString() },
  { productId: 'prod-guinness', quantityOnHand: 32, updatedAt: new Date().toISOString() },
  { productId: 'prod-heineken', quantityOnHand: 18, updatedAt: new Date().toISOString() },
  { productId: 'prod-balozi', quantityOnHand: 24, updatedAt: new Date().toISOString() },
  { productId: 'prod-jw-black', quantityOnHand: 5, updatedAt: new Date().toISOString() },
  { productId: 'prod-jameson', quantityOnHand: 7, updatedAt: new Date().toISOString() },
  { productId: 'prod-gilbeys', quantityOnHand: 9, updatedAt: new Date().toISOString() },
  { productId: 'prod-captain-morgan', quantityOnHand: 6, updatedAt: new Date().toISOString() },
  { productId: 'prod-coke', quantityOnHand: 40, updatedAt: new Date().toISOString() },
  { productId: 'prod-krest', quantityOnHand: 24, updatedAt: new Date().toISOString() },
  { productId: 'prod-redbull', quantityOnHand: 20, updatedAt: new Date().toISOString() },
];
